AWSTemplateFormatVersion: "2010-09-09"
Description: Database and file system
Parameters:
  DataSecurityGroup:
    Type: String
  EfsSecurityGroup:
    Type: String
  DataSubnetAz1:
    Type: String
  DataSubnetAz2:
    Type: String
  DBName:
    Type: String
  RootDBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
Resources:  
  # Elastic file system
  Efs:
    Type: AWS::EFS::FileSystem
    Properties: 
      FileSystemTags:
        - Key: Name
          Value: robust-wp-efs
  MountTargetAz1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Efs
      SecurityGroups:
        [ !Ref DataSecurityGroup, !Ref EfsSecurityGroup ]
      SubnetId: !Ref DataSubnetAz1
  MountTargetAz2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Efs
      SecurityGroups:
        [ !Ref DataSecurityGroup, !Ref EfsSecurityGroup ]
      SubnetId: !Ref DataSubnetAz2
  # Relational data store
  RdsSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: Subnet group for the main RDS instance in robust WP app
      SubnetIds:
        - !Ref DataSubnetAz1
        - !Ref DataSubnetAz2
  RdsCluster:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      AllocatedStorage: 100
      # MultiAZ: true
      DBInstanceClass: db.t2.micro      
      DBName: !Ref DBName
      Engine: mysql
      EngineVersion: 5.6.34
      MasterUsername: !Ref RootDBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RdsSubnetGroup
      Tags:
        - Key: Application
          Value: robust-wp
      VPCSecurityGroups:
        - !Ref DataSecurityGroup
Outputs:
  RdsCluster:
    Value: !GetAtt RdsCluster.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-rds-instance-address"
  Efs:
    Value: !Ref Efs
  MountTargetAz1: 
    Value: !Ref MountTargetAz1
  MountTargetAz2:
    Value: !Ref MountTargetAz2