AWSTemplateFormatVersion: "2010-09-09"
Description: Network
Parameters:
  VpcPrefix:
    Type: String
    Description: VPC prefix i.e. 10.0 for 10.0.0.0/16
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Join [ ".", [ !Ref VpcPrefix , "0.0/16" ] ]
      EnableDnsSupport: true
      EnableDnsHostnames: true
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:        
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Join [ ".", [ !Ref VpcPrefix , "0.0/24" ] ]
      MapPublicIpOnLaunch: true      
      VpcId: !Ref Vpc
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:        
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Join [ ".", [ !Ref VpcPrefix , "1.0/24" ] ]
      MapPublicIpOnLaunch: true      
      VpcId: !Ref Vpc
  InternetGatway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway
  IGWGatewayAttachment:    
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGatway
      VpcId: !Ref Vpc
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref Vpc
  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1
  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2
  InternetRoute:      
    Type: AWS::EC2::Route
    Properties:       
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatway
      RouteTableId: !Ref RouteTable
Outputs:
  Vpc:
    Value: !Ref Vpc
    Export:
      Name: !Sub "${AWS::StackName}-vpc"
  Subnet1:
    Value: !Ref Subnet1
    Export:
      Name: !Sub "${AWS::StackName}-subnet1"
  Subnet2:
    Value: !Ref Subnet2
    Export:
      Name: !Sub "${AWS::StackName}-subnet2"
  VpcPrefix:
    Value: !Ref VpcPrefix
    Export:
      Name: !Sub "${AWS::StackName}-vpc-prefix"
