AWSTemplateFormatVersion: "2010-09-09"
Description: Domain
Parameters:
  DomainName:
    Type: String
Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties: 
      Name: !Ref DomainName
Outputs:
  NameServers:
    Value: !Join ["," , !GetAtt HostedZone.NameServers ]
  HostedZoneId:
    Value: !Ref HostedZone